{"name": "Проверка перехода в раздел История заказов", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <test_user_account.TestUserAccount object at 0x00000206FA065460>, driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"31e23723-02bf-42e4-858e-e1d8b23497d7\")>, login = None\n\n    @allure.title('Проверка перехода в раздел История заказов')\n    def test_redirect_to_order_history(self, driver, login):\n        user_account_page = UserAccountPage(driver)\n>       user_account_page.click_account_btn()\n\ntests\\test_user_account.py:18: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\user_account_page.py:15: in click_account_btn\n    self.find_element(UserAccountLocators.PROFILE_BTN)\npages\\base_page.py:13: in find_element\n    return WebDriverWait(self.driver, 15).until(EC.visibility_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"31e23723-02bf-42e4-858e-e1d8b23497d7\")>, method = <function visibility_of_element_located.<locals>._predicate at 0x00000206FA09E0C0>, message = ''\n\n    def until(self, method: Callable[[WebDriver], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:101: TimeoutException"}, "steps": [{"name": "Клик по кнопке Личный кабинет", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\Евгений\\PycharmProjects\\Diplom\\Diplom_3-develop3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Евгений\\PycharmProjects\\Diplom\\Diplom_3-develop3\\pages\\user_account_page.py\", line 15, in click_account_btn\n    self.find_element(UserAccountLocators.PROFILE_BTN)\n  File \"C:\\Users\\Евгений\\PycharmProjects\\Diplom\\Diplom_3-develop3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Евгений\\PycharmProjects\\Diplom\\Diplom_3-develop3\\pages\\base_page.py\", line 13, in find_element\n    return WebDriverWait(self.driver, 15).until(EC.visibility_of_element_located(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Евгений\\PycharmProjects\\Diplom\\Diplom_3-develop3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 101, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Перемещение до элемента и клик по нему", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', '//*[@href=\"/account\"]')"}], "start": 1727886357288, "stop": 1727886357833}, {"name": "Поиск элемента", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\Евгений\\PycharmProjects\\Diplom\\Diplom_3-develop3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Евгений\\PycharmProjects\\Diplom\\Diplom_3-develop3\\pages\\base_page.py\", line 13, in find_element\n    return WebDriverWait(self.driver, 15).until(EC.visibility_of_element_located(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Евгений\\PycharmProjects\\Diplom\\Diplom_3-develop3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 101, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "('xpath', '//*[@href=\"/account/profile\"]')"}], "start": 1727886357833, "stop": 1727886373011}], "start": 1727886357288, "stop": 1727886373013}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1727886357287, "stop": 1727886373015, "uuid": "93dca5b3-d12e-4663-a267-d55d3cfe129a", "historyId": "d51c5ed1113d9040360077a37f3da516", "testCaseId": "a894cf7308e07d8715b62a9fa4661e1b", "fullName": "tests.test_user_account.TestUserAccount#test_redirect_to_order_history", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_account"}, {"name": "subSuite", "value": "TestUserAccount"}, {"name": "host", "value": "DESKTOP-E2MLG10"}, {"name": "thread", "value": "1900-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_account"}]}